export const metadata = {
  title: "Doran Doran",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <head />
      <body>{children}</body>
    </html>
  );
}
